networks:
    steamexplorer:

services:
    steam-nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: steam_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - steam-php
        networks:
            - steamexplorer

    steam-php:
        build:
            context: ./docker/php/local
            dockerfile: Dockerfile
            args: [ "XDEBUG_CLIENT_HOST=127.0.0.1" ]
        container_name: steam-php
        environment: [ "PHP_IDE_CONFIG=serverName=localhost" ]
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        depends_on:
            -   steam-mysql
        networks:
            - steamexplorer

    steam-mysql:
        image: mysql:9.2.0
        container_name: steam-database
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: steamexplorer
        networks:
            - steamexplorer
